<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.Reactive.Windows.Forms" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa_Entidad\Capa_Entidad.csproj" />
  </ItemGroup>

</Project>
